M3-107 Feat : 안드로이드 걷기 일정 주기 초기화 기능 구현
SWM-M3PRO/GroundFlip-FE pull request #7
Opened 2024-06-22 15:32 UTC by tkdals802

## 작업 내용*
- 걸음수를 일정 기간 동안 초기화 시키도록 구현
## 고민한 내용*
- Pedometer패키지에서 사용하는 Stream에서 전체 걸음수를 받고 
  현재 걸음수 = 전체 걸음수 - 과거 걸음수  그리고 초기화 시킬 때마다 
  과거 걸음수 = 전체 걸음수로 업데이트 시켜주는 과정으로 해결하였다.
- 기술적 고민
   timer로 매 주기마다 계속해서 초기화 시켜 주는것
   Pedometer클래스를 직접 불러와서 걸음수를 가져올 수 없었다.
## 리뷰 요구사항
- 변수, 함수 이름
- 클래스 구조
## 스크린샷

2024-06-23 06:55 UTC, qjvk2880 approved these changes

2024-06-23 06:55 UTC, qjvk2880 commented on lib/screens/map_screen.dart
> +          Obx(() => Text('${AndroidStepController.steps.value}'))
지도 화면에 걸음수가 들어가서 conflict 날 수도 있을 것 같아요!!

2024-06-23 06:57 UTC, koomin1227 requested changes

2024-06-23 06:57 UTC, koomin1227 commented on lib/service/android_walk_interface.dart
> +    // }
주석은 빼고 커밋하는게 좋을거같네요~

2024-06-23 06:57 UTC, koomin1227 commented on lib/screens/map_screen.dart
> +    final AndroidStepCounter AndroidStepController =
지도가 이미 작업되어있어서 이번 이슈에서는 하면에 표시하는 것은 안해도 될거같네요..

2024-06-23 06:57 UTC, koomin1227 commented on lib/service/android_walk_interface.dart
> +class AndroidStepCounter extends GetxController implements WalkingService{
파일이름과 클래스 이름이 다르네여~

2024-06-23 06:57 UTC, koomin1227 commented on lib/service/android_walk_interface.dart
> +  late Stream<StepCount> _stepCountStream;
service 에서 GetX 컨트롤러를 쓰는 거 보다 controller 에서 쓰는게 좋을거 같습니다.

2024-06-23 06:57 UTC, koomin1227 commented on lib/utils/walking_service.dart
> +  void getCurrentStep(StepCount event);
인터페이스가 제 pr 에서도 바꿔서 충돌 날거 같네요

2024-06-23 07:15 UTC, qjvk2880 approved these changes

2024-06-23 07:15 UTC, qjvk2880 commented on lib/service/android_walk_interface.dart
> +  void getCurrentStep(StepCount event){
event를 listen하며 currentStep 멤버변수를 증가시키는 함수를 따로 만들고
getCurrentStep()은 해당 멤버변수를 리턴만 하게끔 하면 어떨까요?

2024-07-07 11:22 UTC, koomin1227 approved these changes

2024-07-07 14:32 UTC, merged